### ISSUE TITLE
Selenium not hitting page

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#37] opened 2015-04-14 03:10 UTC
Giving Selenium a run and have the following test

<pre>

<?php

use Laracasts\Integrated\Extensions\Selenium;

class BatterTest extends Selenium
{

    protected $baseUrl = 'http://www.apple.com';

    /** @test */
    public function it_should_launch_browser()
    {
        $this->visit("/");
    }

}

</pre>

When I run the test, it launches Firefox and then just sits there a while until it finally fails with 

<pre>

1) BatterTest::it_should_launch_browser
WebDriver\Exception\UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

</pre>

**Comment by mikeerickson** [comment] 2015-04-14 03:11
Dont know why my scripts seem to get hammered ...

<?php

use Laracasts\Integrated\Extensions\Selenium;

class BatterTest extends Selenium
{

```
protected $baseUrl = 'http://www.apple.com';

/** @test */
public function it_should_launch_browser()
{
    $this->visit("/");
}
```

}

**Comment by JeffreyWay** [comment] 2015-04-14 03:51
And you have Selenium server up and running?

**Comment by mikeerickson** [comment] 2015-04-14 04:05
Yep, it launches Firefox but doesn't got to any page at all:

I have tried $baseUrl and integrated.json methods for defining location

**Comment by JeffreyWay** [comment] 2015-04-14 05:11
Which version of Selenium are you running? The most recent? 2.45?

**Comment by mikeerickson** [comment] 2015-04-14 05:19
Yes sir 2.45

**Comment by mikeerickson** [comment] 2015-04-14 05:20
I will debug in the morning to see if I can get more details to help this issue along.  

FYI, using Homestead and updated hosts file to hit the URL...

**Comment by JeffreyWay** [comment] 2015-04-14 07:38
Try doing it outside of Homestead, and see if it still happens.

**Comment by mikeerickson** [comment] 2015-04-14 17:34
@JeffreyWay I have done it in both, still no joy.

**Comment by mikeerickson** [comment] 2015-04-14 17:41
@JeffreyWay Well, so far as I can tell, the URL is indeed correct (I have debugged all the way to the point where browser is launched but the defined URL is not used?

**Comment by JeffreyWay** [comment] 2015-04-16 22:11
It's a tough on, because I don't know where to begin debugging. I've never had this happen to me.

**Is anyone else experiencing this? Please chime in, if so.**

**Comment by mikeerickson** [comment] 2015-04-17 00:30
I hear you there, definitely bizarre. I tested w/ behat and it works, go figure.

**Comment by JeffreyWay** [comment] 2015-04-26 02:19
Closing, since no others have chimed in, and I can't reproduce.

**Closed as completed by JeffreyWay** 2015-04-26 02:19 UTC

**Comment by ampersarnie** [comment] 2016-04-04 14:54
@mikeerickson Just want to add to this as I've just had the same issue, but managed to resolve.

The Selenium Standalone Server release (v2.45.0) linked in the [Installation and Setup page](https://github.com/laracasts/Integrated/wiki/Installation-and-Setup) seems to cause the issue. I'm not sure exactly what or how the issue is caused but I managed to resolve it by installing the current latest version (v2.53.0) from the [Selenium website](http://www.seleniumhq.org/download/).
