### ISSUE TITLE
Latest version has seemingly "broken" POST?

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#57] opened 2015-04-24 03:20 UTC
I version 0.14 I was able to have a complete suite of API tests passing with Lumen.

However, with the 0.14.1 update, all my POST tests are failing (they are not passing the data to the controller for further processing?

Has anybody experienced this issue?

The test is as follows:

`
    /** @test  */
    public function it_should_create_batter()
    {
        $data = $this->getSeedData();
        $this->post('/api/v1/batters', $data)
             ->seeJsonContains(['message' => 'Batter Created Successfully']);
    }
`

In the controller, I am retrieving as

`
    // POST /batters
    public function store()
    {
        return $this->api_create($this->model, $this->request->input());
    }
`

but the results from $this->request->input() are blank (empty array)

Any clues?

**Comment by JeffreyWay** [comment] 2015-04-25 16:17
Not sure. I can't reproduce this. All the tests are still returning green. If you have a basic 'hello world' example of how POSTs aren't working anymore, send it through. Otherwise, closing for now.

**Closed as completed by JeffreyWay** 2015-04-25 16:17 UTC

**Comment by mikeerickson** [comment] 2015-04-25 18:07
@JeffreyWay I will create a test application using the latest release and see if I can reproduce it.  Otherwise, I will send you the app I am using that it does not work with.

**Comment by mikeerickson** [comment] 2015-04-25 18:26
@JeffreyWay I have tried with 0.15.0 and issue still occurs.   Please have a look at your laracasts email, that is where I sent it.   If you need more details from me, please let me know.
