### ISSUE TITLE
Any way to press a <button> instead of <input type=submit>

### ISSUE THREAD

**Issue by sameerpanjwani** [laracasts/Integrated#96] opened 2015-06-09 18:22 UTC
Any way to "press" a button <button>, doesn't seem to work.

``` php
use Laracasts\Integrated\Extensions\Selenium;

use Laracasts\Integrated\Services\Laravel\Application as Laravel;

class ValidationTest extends Selenium
{

    use Laravel;

function test_basic_validation()
    {
        $this->visitTestPage()
            ->see('Login')
            ->type('abc@def.com', 'email')
            ->type(' ', 'secret_password')
            ->press('Submit This')
            ->wait(2000)
            ->see("Success")
  }

```

Html

```
<button type="submit">Submit This</button>
```

Error:

```
Curl error thrown for http POST to http://localhost:4444/wd/hub/session/e2d34247-e11f-4a2a-8bed-1f6e79d67d99/element with params: {"using":"css selector","value":"input[value='Submit This']"}
```

**Comment by joedawson** [comment] 2015-06-11 10:38
Could try popping an ID onto the button and using the `click()` method instead?

``` php
$this->click('#buttonID')
```

**Comment by alfredbez** [comment] 2015-06-13 09:27
Seems like this is a duplicate of #85 

@JoeDawson `click` works only for links.

**Comment by joedawson** [comment] 2015-06-13 09:32
@alfredbez that's not correct, as per [the docs](https://github.com/laracasts/Integrated/wiki/Learn-the-API#clicklinktext-or-followlinktext) - I've also been using it this week :)

> While it's easiest if you pass the text content of the desired anchor tag to the click method (like "Sign Up"), you may also use the anchor tag's `name` or `id` attributes if you wish.

**Comment by alfredbez** [comment] 2015-06-15 10:46
@JoeDawson 
From [here](http://symfony.com/doc/current/components/dom_crawler.html#links):

> To find a **link** by name (or a clickable image by its alt attribute), use the selectLink method on an existing crawler.

Or like you already said:

> [...] of the desired **anchor tag** [...]

This is not a link or an anchor tag:

``` html
<button type="submit">Submit This</button>
```

and from [here](https://github.com/laracasts/Integrated/wiki/Learn-the-API#clicklinktext-or-followlinktext):

> Behind the scenes, this package will determine that destination of the link (the "href"), and make a new "GET" request, accordingly.

From [the docs](https://github.com/laracasts/Integrated/wiki/Learn-the-API#presssubmittext)

> Not to be confused with `click`, the `press` method is used to submit a form with a submit button that has the given text.

Please take also a look at the [`click` method (source code)](https://github.com/laracasts/Integrated/blob/master/src/Extensions/IntegrationTrait.php#L221-L242)

**Comment by alfredbez** [comment] 2015-06-15 18:25
Looks like the [`click` method from the Selenium-Extension](https://github.com/laracasts/Integrated/blob/master/src/Extensions/Selenium.php#L80-L105) should work also for other elements, like `button`.

I tried it, but I see the following error:

```
WebDriver\Exception\CurlExec: Curl error thrown for http POST to http://192.168.56.1:4444/wd/hub/session/684d95dc-d3a3-4129-ab75-7ff928c65996/element with params: {"using":"link text","value":"#buttonId"}

The requested URL returned error: 500

/var/www/html/my_project/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
/var/www/html/my_project/vendor/instaclick/php-webdriver/lib/WebDriver/Service/CurlService.php:104
/var/www/html/my_project/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php:123
/var/www/html/my_project/vendor/instaclick/php-webdriver/lib/WebDriver/Container.php:67
/var/www/html/my_project/vendor/laracasts/integrated/src/Extensions/Selenium.php:116
/var/www/html/my_project/vendor/laracasts/integrated/src/Extensions/Selenium.php:91
/var/www/html/my_project/tests/MyTest.php:63

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

Selenium Error:

```
20:06:01.755 WARN - Exception: Unable to locate element: {"method":"link text","selector":"#buttonId"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'HOST', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-37-generic', java.version: '1.7.0_79'

```

PHP-Code:

``` php
$this->visit('/siteWithButton')->click('#buttonId');
```

It works as expected when I swap the lines [91](https://github.com/laracasts/Integrated/blob/d69ca02291b64ea36e9a5f4318db80b032770c2c/src/Extensions/Selenium.php#L91) and [93](https://github.com/laracasts/Integrated/blob/d69ca02291b64ea36e9a5f4318db80b032770c2c/src/Extensions/Selenium.php#L93) or when I use the following code in my test:

``` php
$this->visit('/siteWithButton')->findByNameOrId('#buttonId')->click();
```

**Comment by alfredbez** [comment] 2015-06-16 12:29
I came up with the following solution:

I created an abstract Test Class which extends the Selenium Extension Class.

It looks like this:

``` php
<?php

use Laracasts\Integrated\Extensions\Selenium as IntegrationTest;

abstract class AbstractSeleniumTest extends IntegrationTest {

  protected function findByCssSelector($selector)
  {
      try {
          return $this->session->element('css selector', $selector);
      } catch (NoSuchElement $e) {
          throw new InvalidArgumentException(
              "Couldn't find an element, matching the follwing css selector: '{$seletor}'."
          );
      }
  }

  public function clickCss($selector)
  {
    $this->findByCssSelector($selector)->click();

    return $this;
  }

}
```

It gives me a more flexible way to click on elements, e.g.

``` php
$this->clickCss("#someElement + button");
```

``` html
<div id="someElement">an Element</div>
<button>I have no ID and name!</button>
```

**Closed as completed** 2015-08-20 03:37 UTC
